/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthInviteRouteImport } from './routes/auth/invite'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardWorkersRouteImport } from './routes/_dashboard/workers'
import { Route as DashboardProjectsRouteImport } from './routes/_dashboard/projects'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardPagesRouteImport } from './routes/_dashboard/pages'
import { Route as DashboardDeploymentsRouteImport } from './routes/_dashboard/deployments'
import { Route as DashboardDatabasesRouteImport } from './routes/_dashboard/databases'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCronjobsRouteImport } from './routes/_dashboard/cronjobs'
import { Route as DashboardAppsRouteImport } from './routes/_dashboard/apps'
import { Route as DashboardAdminRouteImport } from './routes/_dashboard/admin'
import { Route as AuthLoginNotAdminRouteImport } from './routes/auth/login_.not-admin'
import { Route as DashboardProjectsIdRouteImport } from './routes/_dashboard/projects_/$id'
import { Route as DashboardAdminVolumesRouteImport } from './routes/_dashboard/admin/volumes'
import { Route as DashboardAdminTraefikRouteImport } from './routes/_dashboard/admin/traefik'
import { Route as DashboardAdminTeamsRouteImport } from './routes/_dashboard/admin/teams'
import { Route as DashboardAdminSettingsRouteImport } from './routes/_dashboard/admin/settings'
import { Route as DashboardAdminResourcesRouteImport } from './routes/_dashboard/admin/resources'
import { Route as DashboardAdminClusterRouteImport } from './routes/_dashboard/admin/cluster'
import { Route as DashboardProjectsIdIndexRouteImport } from './routes/_dashboard/projects_/$id/index'
import { Route as DashboardProjectsIdWorkersWorkerIdRouteImport } from './routes/_dashboard/projects_/$id/workers.$workerId'
import { Route as DashboardProjectsIdPagesPageIdRouteImport } from './routes/_dashboard/projects_/$id/pages.$pageId'
import { Route as DashboardProjectsIdDatabasesDbIdRouteImport } from './routes/_dashboard/projects_/$id/databases.$dbId'
import { Route as DashboardProjectsIdAppsAppIdRouteImport } from './routes/_dashboard/projects_/$id/apps.$appId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/auth/invite',
  path: '/auth/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkersRoute = DashboardWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPagesRoute = DashboardPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatabasesRoute = DashboardDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCronjobsRoute = DashboardCronjobsRouteImport.update({
  id: '/cronjobs',
  path: '/cronjobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsRoute = DashboardAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthLoginNotAdminRoute = AuthLoginNotAdminRouteImport.update({
  id: '/auth/login_/not-admin',
  path: '/auth/login/not-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/projects_/$id',
  path: '/projects/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminVolumesRoute = DashboardAdminVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminTraefikRoute = DashboardAdminTraefikRouteImport.update({
  id: '/traefik',
  path: '/traefik',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminTeamsRoute = DashboardAdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminResourcesRoute = DashboardAdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminClusterRoute = DashboardAdminClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardProjectsIdIndexRoute =
  DashboardProjectsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdWorkersWorkerIdRoute =
  DashboardProjectsIdWorkersWorkerIdRouteImport.update({
    id: '/workers/$workerId',
    path: '/workers/$workerId',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdPagesPageIdRoute =
  DashboardProjectsIdPagesPageIdRouteImport.update({
    id: '/pages/$pageId',
    path: '/pages/$pageId',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdDatabasesDbIdRoute =
  DashboardProjectsIdDatabasesDbIdRouteImport.update({
    id: '/databases/$dbId',
    path: '/databases/$dbId',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdAppsAppIdRoute =
  DashboardProjectsIdAppsAppIdRouteImport.update({
    id: '/apps/$appId',
    path: '/apps/$appId',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof DashboardAdminRouteWithChildren
  '/apps': typeof DashboardAppsRoute
  '/cronjobs': typeof DashboardCronjobsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/databases': typeof DashboardDatabasesRoute
  '/deployments': typeof DashboardDeploymentsRoute
  '/pages': typeof DashboardPagesRoute
  '/profile': typeof DashboardProfileRoute
  '/projects': typeof DashboardProjectsRoute
  '/workers': typeof DashboardWorkersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/cluster': typeof DashboardAdminClusterRoute
  '/admin/resources': typeof DashboardAdminResourcesRoute
  '/admin/settings': typeof DashboardAdminSettingsRoute
  '/admin/teams': typeof DashboardAdminTeamsRoute
  '/admin/traefik': typeof DashboardAdminTraefikRoute
  '/admin/volumes': typeof DashboardAdminVolumesRoute
  '/projects/$id': typeof DashboardProjectsIdRouteWithChildren
  '/auth/login/not-admin': typeof AuthLoginNotAdminRoute
  '/projects/$id/': typeof DashboardProjectsIdIndexRoute
  '/projects/$id/apps/$appId': typeof DashboardProjectsIdAppsAppIdRoute
  '/projects/$id/databases/$dbId': typeof DashboardProjectsIdDatabasesDbIdRoute
  '/projects/$id/pages/$pageId': typeof DashboardProjectsIdPagesPageIdRoute
  '/projects/$id/workers/$workerId': typeof DashboardProjectsIdWorkersWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof DashboardAdminRouteWithChildren
  '/apps': typeof DashboardAppsRoute
  '/cronjobs': typeof DashboardCronjobsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/databases': typeof DashboardDatabasesRoute
  '/deployments': typeof DashboardDeploymentsRoute
  '/pages': typeof DashboardPagesRoute
  '/profile': typeof DashboardProfileRoute
  '/projects': typeof DashboardProjectsRoute
  '/workers': typeof DashboardWorkersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/cluster': typeof DashboardAdminClusterRoute
  '/admin/resources': typeof DashboardAdminResourcesRoute
  '/admin/settings': typeof DashboardAdminSettingsRoute
  '/admin/teams': typeof DashboardAdminTeamsRoute
  '/admin/traefik': typeof DashboardAdminTraefikRoute
  '/admin/volumes': typeof DashboardAdminVolumesRoute
  '/auth/login/not-admin': typeof AuthLoginNotAdminRoute
  '/projects/$id': typeof DashboardProjectsIdIndexRoute
  '/projects/$id/apps/$appId': typeof DashboardProjectsIdAppsAppIdRoute
  '/projects/$id/databases/$dbId': typeof DashboardProjectsIdDatabasesDbIdRoute
  '/projects/$id/pages/$pageId': typeof DashboardProjectsIdPagesPageIdRoute
  '/projects/$id/workers/$workerId': typeof DashboardProjectsIdWorkersWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/_dashboard/apps': typeof DashboardAppsRoute
  '/_dashboard/cronjobs': typeof DashboardCronjobsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/databases': typeof DashboardDatabasesRoute
  '/_dashboard/deployments': typeof DashboardDeploymentsRoute
  '/_dashboard/pages': typeof DashboardPagesRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/projects': typeof DashboardProjectsRoute
  '/_dashboard/workers': typeof DashboardWorkersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_dashboard/admin/cluster': typeof DashboardAdminClusterRoute
  '/_dashboard/admin/resources': typeof DashboardAdminResourcesRoute
  '/_dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/_dashboard/admin/teams': typeof DashboardAdminTeamsRoute
  '/_dashboard/admin/traefik': typeof DashboardAdminTraefikRoute
  '/_dashboard/admin/volumes': typeof DashboardAdminVolumesRoute
  '/_dashboard/projects_/$id': typeof DashboardProjectsIdRouteWithChildren
  '/auth/login_/not-admin': typeof AuthLoginNotAdminRoute
  '/_dashboard/projects_/$id/': typeof DashboardProjectsIdIndexRoute
  '/_dashboard/projects_/$id/apps/$appId': typeof DashboardProjectsIdAppsAppIdRoute
  '/_dashboard/projects_/$id/databases/$dbId': typeof DashboardProjectsIdDatabasesDbIdRoute
  '/_dashboard/projects_/$id/pages/$pageId': typeof DashboardProjectsIdPagesPageIdRoute
  '/_dashboard/projects_/$id/workers/$workerId': typeof DashboardProjectsIdWorkersWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apps'
    | '/cronjobs'
    | '/dashboard'
    | '/databases'
    | '/deployments'
    | '/pages'
    | '/profile'
    | '/projects'
    | '/workers'
    | '/auth/callback'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/register'
    | '/admin/cluster'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/traefik'
    | '/admin/volumes'
    | '/projects/$id'
    | '/auth/login/not-admin'
    | '/projects/$id/'
    | '/projects/$id/apps/$appId'
    | '/projects/$id/databases/$dbId'
    | '/projects/$id/pages/$pageId'
    | '/projects/$id/workers/$workerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apps'
    | '/cronjobs'
    | '/dashboard'
    | '/databases'
    | '/deployments'
    | '/pages'
    | '/profile'
    | '/projects'
    | '/workers'
    | '/auth/callback'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/register'
    | '/admin/cluster'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/traefik'
    | '/admin/volumes'
    | '/auth/login/not-admin'
    | '/projects/$id'
    | '/projects/$id/apps/$appId'
    | '/projects/$id/databases/$dbId'
    | '/projects/$id/pages/$pageId'
    | '/projects/$id/workers/$workerId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/admin'
    | '/_dashboard/apps'
    | '/_dashboard/cronjobs'
    | '/_dashboard/dashboard'
    | '/_dashboard/databases'
    | '/_dashboard/deployments'
    | '/_dashboard/pages'
    | '/_dashboard/profile'
    | '/_dashboard/projects'
    | '/_dashboard/workers'
    | '/auth/callback'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/register'
    | '/_dashboard/admin/cluster'
    | '/_dashboard/admin/resources'
    | '/_dashboard/admin/settings'
    | '/_dashboard/admin/teams'
    | '/_dashboard/admin/traefik'
    | '/_dashboard/admin/volumes'
    | '/_dashboard/projects_/$id'
    | '/auth/login_/not-admin'
    | '/_dashboard/projects_/$id/'
    | '/_dashboard/projects_/$id/apps/$appId'
    | '/_dashboard/projects_/$id/databases/$dbId'
    | '/_dashboard/projects_/$id/pages/$pageId'
    | '/_dashboard/projects_/$id/workers/$workerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthInviteRoute: typeof AuthInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthLoginNotAdminRoute: typeof AuthLoginNotAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/invite': {
      id: '/auth/invite'
      path: '/auth/invite'
      fullPath: '/auth/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/workers': {
      id: '/_dashboard/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof DashboardWorkersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects': {
      id: '/_dashboard/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pages': {
      id: '/_dashboard/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof DashboardPagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/deployments': {
      id: '/_dashboard/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/databases': {
      id: '/_dashboard/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DashboardDatabasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/cronjobs': {
      id: '/_dashboard/cronjobs'
      path: '/cronjobs'
      fullPath: '/cronjobs'
      preLoaderRoute: typeof DashboardCronjobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps': {
      id: '/_dashboard/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof DashboardAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin': {
      id: '/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/login_/not-admin': {
      id: '/auth/login_/not-admin'
      path: '/auth/login/not-admin'
      fullPath: '/auth/login/not-admin'
      preLoaderRoute: typeof AuthLoginNotAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/projects_/$id': {
      id: '/_dashboard/projects_/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/volumes': {
      id: '/_dashboard/admin/volumes'
      path: '/volumes'
      fullPath: '/admin/volumes'
      preLoaderRoute: typeof DashboardAdminVolumesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/traefik': {
      id: '/_dashboard/admin/traefik'
      path: '/traefik'
      fullPath: '/admin/traefik'
      preLoaderRoute: typeof DashboardAdminTraefikRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/teams': {
      id: '/_dashboard/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof DashboardAdminTeamsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/settings': {
      id: '/_dashboard/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/resources': {
      id: '/_dashboard/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof DashboardAdminResourcesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/cluster': {
      id: '/_dashboard/admin/cluster'
      path: '/cluster'
      fullPath: '/admin/cluster'
      preLoaderRoute: typeof DashboardAdminClusterRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/projects_/$id/': {
      id: '/_dashboard/projects_/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof DashboardProjectsIdIndexRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/_dashboard/projects_/$id/workers/$workerId': {
      id: '/_dashboard/projects_/$id/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/projects/$id/workers/$workerId'
      preLoaderRoute: typeof DashboardProjectsIdWorkersWorkerIdRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/_dashboard/projects_/$id/pages/$pageId': {
      id: '/_dashboard/projects_/$id/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/projects/$id/pages/$pageId'
      preLoaderRoute: typeof DashboardProjectsIdPagesPageIdRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/_dashboard/projects_/$id/databases/$dbId': {
      id: '/_dashboard/projects_/$id/databases/$dbId'
      path: '/databases/$dbId'
      fullPath: '/projects/$id/databases/$dbId'
      preLoaderRoute: typeof DashboardProjectsIdDatabasesDbIdRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/_dashboard/projects_/$id/apps/$appId': {
      id: '/_dashboard/projects_/$id/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/projects/$id/apps/$appId'
      preLoaderRoute: typeof DashboardProjectsIdAppsAppIdRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminClusterRoute: typeof DashboardAdminClusterRoute
  DashboardAdminResourcesRoute: typeof DashboardAdminResourcesRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminTeamsRoute: typeof DashboardAdminTeamsRoute
  DashboardAdminTraefikRoute: typeof DashboardAdminTraefikRoute
  DashboardAdminVolumesRoute: typeof DashboardAdminVolumesRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminClusterRoute: DashboardAdminClusterRoute,
  DashboardAdminResourcesRoute: DashboardAdminResourcesRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminTeamsRoute: DashboardAdminTeamsRoute,
  DashboardAdminTraefikRoute: DashboardAdminTraefikRoute,
  DashboardAdminVolumesRoute: DashboardAdminVolumesRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardProjectsIdRouteChildren {
  DashboardProjectsIdIndexRoute: typeof DashboardProjectsIdIndexRoute
  DashboardProjectsIdAppsAppIdRoute: typeof DashboardProjectsIdAppsAppIdRoute
  DashboardProjectsIdDatabasesDbIdRoute: typeof DashboardProjectsIdDatabasesDbIdRoute
  DashboardProjectsIdPagesPageIdRoute: typeof DashboardProjectsIdPagesPageIdRoute
  DashboardProjectsIdWorkersWorkerIdRoute: typeof DashboardProjectsIdWorkersWorkerIdRoute
}

const DashboardProjectsIdRouteChildren: DashboardProjectsIdRouteChildren = {
  DashboardProjectsIdIndexRoute: DashboardProjectsIdIndexRoute,
  DashboardProjectsIdAppsAppIdRoute: DashboardProjectsIdAppsAppIdRoute,
  DashboardProjectsIdDatabasesDbIdRoute: DashboardProjectsIdDatabasesDbIdRoute,
  DashboardProjectsIdPagesPageIdRoute: DashboardProjectsIdPagesPageIdRoute,
  DashboardProjectsIdWorkersWorkerIdRoute:
    DashboardProjectsIdWorkersWorkerIdRoute,
}

const DashboardProjectsIdRouteWithChildren =
  DashboardProjectsIdRoute._addFileChildren(DashboardProjectsIdRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardAppsRoute: typeof DashboardAppsRoute
  DashboardCronjobsRoute: typeof DashboardCronjobsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDatabasesRoute: typeof DashboardDatabasesRoute
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRoute
  DashboardPagesRoute: typeof DashboardPagesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardWorkersRoute: typeof DashboardWorkersRoute
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardAppsRoute: DashboardAppsRoute,
  DashboardCronjobsRoute: DashboardCronjobsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDatabasesRoute: DashboardDatabasesRoute,
  DashboardDeploymentsRoute: DashboardDeploymentsRoute,
  DashboardPagesRoute: DashboardPagesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardWorkersRoute: DashboardWorkersRoute,
  DashboardProjectsIdRoute: DashboardProjectsIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthInviteRoute: AuthInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthLoginNotAdminRoute: AuthLoginNotAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
